GET localhost:3001/info
###

GET localhost:3001/api/persons

# @lang=lua
> {%
local body = vim.json.decode(response.body)
client.global.set("personId",body[1].id)
%}
###

POST localhost:3001/api/persons
Content-Type: application/json

{"name":"boba","number":"123"}
###

#Collision
POST localhost:3001/api/persons
Content-Type: application/json

{"name":"boba","number":"321"}



DELETE localhost:3001/api/persons/{{personId}}







